name: CI

on:
  push:
  pull_request:

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        continue-on-error: true
      - name: List repo
        run: ls -R
